<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Prueba</title>
    <link rel="stylesheet" href="public/css/css.css" type="text/css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
 </head>
<body >
    <div class="row">
        <div class="col-lg-12">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="text text-center text-primary"> Prueba </h2>
                </div>
                <div class="col-lg-12">
                    <hr>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="row">
                        <div class="col-lg-12">
                            <h3 class="text text-secondary text-center">Ingresar Nuevo Cliente</h3>
                        </div>
                        <div class="col-lg-12"><hr></div>
                    </div>
                    <div class="row">
                        <div class="col-lg-1"></div>
                        <div class="col-lg-5">
                            <label for="nombre">Ingrese Nombre</label><br/>
                            <input type="text" name="nombre" id="nombre"/>
                            
                        </div>
                        <div class="col-lg-5" >
                            <label for="apellido">Ingrese Apellido</label><br/>
                            <input type="text" name="apellido" id="apellido"/>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-1"></div>
                        <div class="col-lg-3">
                            <a id="send" class="btn btn-primary"> <span class="text text-white">Agregar Cliente</span></a>
                        </div>
                        <div class="col-lg-2"></div>
                        <div class="col-lg-3">
                            <a id="xml" class="btn btn-primary"> <span class="text text-white">Exportar a XML</span></a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="row">
                        <div class="col-lg-12">
                            <h3 class="text text-secondary text-center">Clientes ingresados</h3>
                        </div>
                        <div class="col-lg-12"><hr></div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="col-lg-1"></div>
                            <div class="col-lg-10">
                                <table id="tabla" class="table table-hover" >
                                    <thead class="thead-light">
                                        <tr>
                                            <th>ID</th>
                                            <th>Nombre</th>
                                        </tr>
                                    </thead>
                                    <tbody id="cuerpo">
                                    </tbody>
                                </table>
                                
                            <div class="col-lg-1"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="labelmodal" aria-hidden="true">
	    <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h3 class="modal-title" id="nombrec"></h3>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="row">
                <div class="col-lg-6">
                    <div class="row">
                        <div class="col-lg-12">
                            <h4 class="text text-muted text-center"> Direcciones</h4>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <table class="table">
                                <tbody id="cuerpodirecciones">
                                    
                                </tbody>
                            </table>
                        </div>
                        <div class="row">
                            <div class="col-lg-1"></div>
                            <div class="col-lg-3">
                                <input type="text" name="direc" id="direc"/>
                            </div>
                            <div class="col-lg-2"></div>
                            <div class="col-lg-3">
                                <a class="btn btn-primary" id="sed"> <span class="text-white">add Dirección</span> </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="row">
                        <div class="col-lg-12">
                            <h4 class="text text-muted text-center"> Teléfonos</h4>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <table class="table">
                                <tbody id="cuerpotelefono">
                                    
                                </tbody>
                            </table>
                        </div>
                        <div class="row">
                            <div class="col-lg-1"></div>
                            <div class="col-lg-3">
                                <input type="text" class="input" name="tel" id="tel"/>
                            </div>
                            <div class="col-lg-2"></div>
                            <div class="col-lg-3">
                                <a class="btn btn-primary" id="sen"> <span class="text-white">add Número</span> </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
          </div>
        </div>
      </div>
	</div>
</div>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="public/js/js.js"></script>
    
</body>
</html>
